Feature/is fresh
ridi/django-shard-library pull request #35
Opened 2018-07-09 10:08 UTC by antiline

- Add get shard command
- Add is_fresh

2018-07-09 12:38 UTC, JungleKim requested changes

2018-07-09 12:38 UTC, JungleKim commented on shard/management/commands/get_shard_command.py
> +            dest='shard key',
Must change to `shard_key`.

2018-07-09 12:38 UTC, JungleKim commented on shard/management/commands/get_shard_command.py
> +    def assert_if_params_are_not_valid(**options):
This method is unnecessary.

`argparse` module include `required` option. 
If `required` is True and parameter is null, can't passing validation.

You don't have to write additional code.

2018-07-10 02:47 UTC, antiline commented
@JungleKim  I fixed it.

2018-07-10 03:50 UTC, JungleKim approved these changes

2018-07-10 05:12 UTC, merged